---
title: "Events & Presentations"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Upcoming

- [3rd Marine Biodiversity Workshop: from the Sea to the Cloud](http://marinebon.org/p2p-colombia-workshop/) - May 4-8, 2020, Santa Marta, Colombia.

## Past

- [AGU Fall Meeting 2019](https://www2.agu.org/fall-meeting) - December 9-13, 2019, San Francisco, California. The MBON Pole to Pole absctract is available [here](https://drive.google.com/file/d/17deXPg_umFPoeYPB6QKTLDfwqv7hBUmG/view?usp=sharing).

- [10ª Semana de Integração Acadêmica da UFRJ / SIAC](http://siac.ufrj.br/) - October 21-27, 2019, Rio de Janeiro, Brazil. A poster on sandy beach biodiversity is available [here](https://drive.google.com/file/d/1fTgRFdOIGuESTIFHzMmO-nYa0KF4DOMc/view?usp=sharing)

- [OceanObs'19](http://www.oceanobs19.net/) - September 16-20, 2019. Check out posters on [MBON Pole to Pole](https://drive.google.com/file/d/1AWpEQSBzLOAGapNOh1J3KQwkB4GTVFXQ/view?usp=sharing) and [biodiversity monitoring and citizen science](https://drive.google.com/file/d/1BHuRr4WBTZIqBvBYphcUs9birViUnN5X/view?usp=sharing).  

- [MBON Pole to Pole presentation](https://usf.app.box.com/s/08569c61yektdv3odcgwuy5x1cmvuy8p) for the Global MBON monthly webinar - September 9, 2019. 

- [2019 AmeriGEO Week](https://www.amerigeoss.org/amerigeoss-events/amerigeoss-week-2019) - August 19-23, 2019, Lima, Peru. The MBON Pole to Pole will be represented at the AmeriGEO Week by [IMARPE](http://www.imarpe.gob.pe/imarpe/)

- [XIII Biofouling, Benthic Ecology and Marine Biotechnology Meeting](https://xiiibioinc.wixsite.com/xiiibioinc) - August 5-9, 2019, Arraial do Cabo, Rio de Janeiro, Brazil. The MBON Pole to Pole poster is available [here](https://drive.google.com/file/d/1AVl5loMTuzkE_xdBw9d-J7HNMojO_v9F/view?usp=sharing)

- [XXXIX Congreso de Ciencias del Mar “Recuperación y protección de la biodiversidad en un escenario de cambio global”](https://www.congresocienciasdelmar.cl/)<br>
May 27-31, 2019, Iquique, Chile. The MBON Pole to Pole absctract is available [here](https://drive.google.com/file/d/1V5ZDpoSoY9vU3MFXR6tVSro6Uaab4PZh/view?usp=sharing). Presentation slides are also available [here](https://drive.google.com/file/d/1V3j9ZRAJg0ycXsPYmUWyNw4Hx7trJLeW/view?usp=sharing).

- [NASA Biodiversity and Ecological Forecasting Meeting](https://drive.google.com/file/d/1fxq8MvqTIWO_N1hUmw11F4L4u6AsyNuG/view?usp=sharing)<br> 2019-05-22 in Washington DC, USA

- [2nd Marine Biodiversity Workshop: from the Sea to the Cloud](https://marinebon.github.io/p2p-mexico-workshop/)<br>
  2019-04-02 in Puerto Morelos, Mexico
  
- [American Gephysical Union Fall Meeting 2018](https://drive.google.com/file/d/1YFOOYFZNmNTGzK3BRestIS1RltkZImEu/view?usp=sharing)<br>
  2018-12-10 in Washington DC, USA

- [Marine Biodiversity Workshop: from the Sea to the Cloud](https://marinebon.github.io/p2p-brazil-workshop/)<br>
  2018-08-06 in São Sebastião, Brazil


