---
title: "MBON Pole to Pole Project"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```
<br>
<br>
<font size="5"> 
Welcome! We are developing a Community of Practice across the Americas to assess marine biodiversity and ecosystem change using field and space observations.
<br>
<br>
Ongoing biodiversity monitoring sites  

```{r}
library(tidyverse)
library(rnaturalearth) # install.packages("rnaturalearth")
library(sf)
library(leaflet)
library(here)
library(glue)
library(htmltools)

countries <- ne_countries(
  scale = "small", type = "countries", returnclass = "sf",
  continent= c("North America", "South America")) %>%
  mutate(
    mapcolor7 = as.factor(as.character(mapcolor7)))

sites_csv <- here("data/sites.csv")

sites <- read_csv(sites_csv) %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

b <- sf::st_bbox(sites)

pal <- colorFactor("Set2", countries$mapcolor7)
```


```{r original map, eval=F}
leaflet(countries) %>%
  addProviderTiles(
    providers$Esri.OceanBasemap, 
    options = providerTileOptions(opacity = 0.5)) %>%
  addPolygons(
    stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.8,
    fillColor = ~pal(mapcolor7),
    label = ~admin) %>% 
  addMarkers(
    data = sites, 
    popup = ~htmlEscape(name), label = ~htmlEscape(name)) %>% 
  fitBounds(b[['xmin']], b[['ymin']], b[['xmax']], b[['ymax']])
```

```{r}
library(htmltools)
library(markdown)

sites <- read_csv(sites_csv) %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326) %>% 
  mutate(
    md = glue("**{name}**<br>Org: {org}<br>Country: {str_to_upper(country)}<br>↪[ Visit](site/{id}.html)"),
    html = map_chr(md, function(x) HTML(markdownToHTML(text=x, fragment.only=T))))
View(sites)

leaflet(countries) %>%
  addProviderTiles(
    providers$Esri.OceanBasemap, 
    options = providerTileOptions(opacity = 0.5)) %>%
  addPolygons(
    stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.8,
    fillColor = ~pal(mapcolor7),
    label = ~admin) %>% 
  addMarkers(
    data = sites, 
    popup = ~html, label = ~htmlEscape(name)) %>% 
  fitBounds(b[['xmin']], b[['ymin']], b[['xmax']], b[['ymax']])
```


```{r p2p sparkline1, eval=F}
leaflet(countries) %>%
  addProviderTiles(
    providers$Esri.OceanBasemap, 
    options = providerTileOptions(opacity = 0.5)) %>%
  addPolygons(
    stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.8,
    fillColor = ~pal(mapcolor7),
    label = ~admin) %>% 
  addMarkers(
    data = sites, 
    #popup = ~htmlEscape(name), label = ~htmlEscape(name)) %>% 
    popup = lapply(seq_along(sites),function(x) {
      as.character(
        tags$div(
          style="height:200px;width:300px;",
          sparkline(runif(20), height=200, width=300)
        )
      )
    })
  ) %>% 
  fitBounds(b[['xmin']], b[['ymin']], b[['xmax']], b[['ymax']]) %>% 
  onRender(
"
function(el,x) {
  this.on('popupopen', function() {HTMLWidgets.staticRender();})
}
") %>%
  add_deps("sparkline") %>%
  browsable()
```

```{r p2p dygraphs, eval=F}
library(dygraphs)

#dygraph(nhtemp, main = "New Haven Temperatures") %>% 
#  dyRangeSelector(dateWindow = c("1920-01-01", "1960-01-01"))

sites <- read_csv(sites_csv) %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326) %>% 
  slice(1:4)

source("functions.R")
#popup_site_sst("sa-fknms", width = 300, height = 200)

sites <- sites %>% 
  mutate(plot = map_chr(id, popup_site_sst, width = 300, height = 200))
         
leaflet(countries) %>%
  addProviderTiles(
    providers$Esri.OceanBasemap, 
    options = providerTileOptions(opacity = 0.5)) %>%
  addPolygons(
    stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.8,
    fillColor = ~pal(mapcolor7),
    label = ~admin) %>% 
  addMarkers(
    data = sites, 
    #popup = ~htmlEscape(name), label = ~htmlEscape(name)) %>% 
    popup = ~plot) %>% 
    # popup = lapply(seq_along(sites),function(x) {
    #   as.character(
    #     #tags$div(
    #       #style="height:200px;width:300px;",
    #       dygraph(
    #         nhtemp, main = "New Haven Temperatures",
    #         width = 300, height = 200) #) #%>% 
    #         #dyRangeSelector(dateWindow = c("1920-01-01", "1960-01-01")))
    #     )})) %>% 
  fitBounds(b[['xmin']], b[['ymin']], b[['xmax']], b[['ymax']]) %>% 
  onRender(
"
function(el,x) {
  this.on('popupopen', function() {HTMLWidgets.staticRender();})
}
") %>%
  add_deps("dygraphs") %>%
  browsable()
```

```{r, eval=F}
library(leaflet) # 1.1
library(htmlwidgets)
library(htmltools)
library(plotly)
library(sparkline)
library(mapview)

# Step 1 convert htmlwidget to character representation of HTML components
as.character.htmlwidget <- function(x, ...) {
  htmltools::HTML(
    htmltools:::as.character.shiny.tag.list(
      htmlwidgets:::as.tags.htmlwidget(
        x
      ),
      ...
    )
  )
}

add_deps <- function(dtbl, name, pkg = name) {
  tagList(
    dtbl,
    htmlwidgets::getDependency(name, pkg)
  )
}

df <- read.csv(textConnection(
  "Name,Lat,Long
  Samurai Noodle,47.597131,-122.327298
  Kukai Ramen,47.6154,-122.327157
  Tsukushinbo,47.59987,-122.326726"
))

leaflet(df) %>% 
  addTiles() %>% 
  #addMouseCoordinates() %>%
  addMarkers(
    ~Long, ~Lat,
      popup = lapply(seq_along(df),function(x) {
      as.character(
        tags$div(
          style="height:200px;width:300px;",
          sparkline(runif(20), height=200, width=300)
        )
      )
    })
  ) %>%
  onRender(
"
function(el,x) {
  this.on('popupopen', function() {HTMLWidgets.staticRender();})
}
") %>%
  add_deps("sparkline") %>%
  browsable()

```

```{r, eval=F}
leaflet(df) %>% 
  addTiles() %>%
  addMarkers(
    ~Long, ~Lat,
    popup = lapply(
      seq_along(df),
      function(x) {
        plot_ly(x=~1:20, y=~runif(20)) %>% # put in meaningful data e.g weather by month
          add_markers() %>%
          as.tags() %>%
          {tags$div(style="width:300px;", .)} %>%
          as.character()
      }
    )
  ) %>%
  onRender(
"
function(el,x) {
  this.on('popupopen', function() {HTMLWidgets.staticRender();})
}
") %>%
  add_deps("plotly") %>%
  #htmltools::attachDependencies(crosstalk::crosstalkLibs()) %>%
  browsable()
```

```{r, eval=F}
library(listviewer)

leaflet(df) %>% addTiles() %>%
  addMarkers(
    ~Long, ~Lat,
    popup = lapply(
      seq_along(df),
      function(i){
        as.character(
          jsonedit(
            jsonlite::toJSON(df[i,,drop=TRUE],auto_unbox=TRUE),
            height=200,width=300
          )
        )
      }
    )
  ) %>%
  onRender(
"
function(el,x) {
  this.on('popupopen', function() {HTMLWidgets.staticRender();})
}
") %>%
  add_deps("jsonedit", "listviewer") %>%
  browsable()
```

