---
title: "Site: `r params$site_name`"
params:
  site_name: "Puntilla de Sta Elena - Chocolatera" # "Pass-a-Grille"
  site_id: "ecu-puntilladestaelena-chocolatera" # "usa-usfstpete"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE, echo=F}
library(tidyverse)
library(knitr)
library(leaflet)
library(mapview)
library(bsplus)
source("functions.R")

# params = list(site_id="usa-fknms")
# params = list(site_id="col-islagorgona-lamancora")
# params = list(site_id="bra-costadasalgas-gramute")
# params = list(
#   site_id="ecu-puntilladestaelena-chocolatera",
#   site_name="Puntilla de Sta Elena - Chocolatera")
```

```{r get_csv_data, include=FALSE, echo=FALSE}
site <- read_csv(here("data/sites.csv")) %>%
  filter(id == params$site_id)
photos <- read_csv(here("data/site_photos.csv")) %>%
  filter(id == params$site_id)
```

```{r fetch_erddap_info, include=FALSE, echo=FALSE}
sst <- info('jplMURSST41mday')
chl <- info("nesdisVHNSQchlaMonthly")
```

- Country: **`r str_to_upper(site$country)`**
- Organization: **`r site$org`**

## Photos

```{r, echo=FALSE}
if (nrow(photos) > 0){
  carousel <- bs_carousel(id = "photos", use_indicators = TRUE)

  for (i in 1:nrow(photos)){
    photo <- photos[i,]
    carousel <-  bs_append(
      carousel,
      content = bs_carousel_image(src = photo$url),
      caption = bs_carousel_caption(photo$caption))
  }

  carousel
} else {
  cat("No photos yet posted.")
}
```

## Map of SST

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# get most recent date
d <- get_dates(sst)[2]
```

Map of the most recent (`r format(d,"%Y-%m-%d")`) sea-surface temperature (SST) around the site.

```{r, echo=FALSE}
# box <- get_box(site$lon, site$lat, cells_wide=10)
# r   <- get_raster(sst, lon=box$lon, lat=box$lat, date="last", field="sst")
# map_raster(r, site_lon=site$lon, site_lat=site$lat, site_label=site$name, title="SST")

# bounding box offset around site marker for extent of map
b <- 3.0

leaflet(
  options = leafletOptions(
    crs = leafletCRS(crsClass = "L.CRS.EPSG4326"))) %>%
  # basemap from GBIF in 4326
  addTiles("//tile.gbif.org/4326/omt/{z}/{x}/{y}@1x.png?style=gbif-geyser") %>%
  # sst
  addWMSTiles(
    baseUrl = 'https://coastwatch.pfeg.noaa.gov/erddap/wms/jplMURSST41mday/request?',
    layers = "jplMURSST41mday:sst",
    options = WMSTileOptions(
      version = "1.3.0", format = "image/png", transparent = T, opacity = 0.7,
      time = format(d,"%Y-%m-%dT00:00:00Z")))  %>%
  addMarkers(lng = ~lon, lat = ~lat, label = ~name, data=site) %>%
  addMouseCoordinates() %>%
  fitBounds(site$lon - b, site$lat - b, site$lon + b, site$lat + b) %>%
  addLegend(
    position="bottomright",
    title = paste0("SST (°C)<br>", format(d,"%Y-%m-%d")),
    colorNumeric("Spectral", c(0,32), reverse=T), seq(0,32))
```

## Timeseries of SST

```{r, echo=FALSE, message=FALSE, warning=FALSE}
csv <- here(glue("data/sst/sst_{site$id}.csv"))
d   <- get_timeseries(sst, lon=site$lon, lat=site$lat, csv=csv, field="sst")
plot_timeseries(d, title="SST", color="red")
```

## Map of CHL

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# get most recent date
d_2 <- get_dates(chl)[2]
```

Map of the most recent (`r format(d_2, "%Y-%m-%d")`) Chlorophyll-a (CHL) around the site.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# box_2 <- get_box(site$lon, site$lat, cells_wide=10)
# r_2   <- get_raster(chl, lon=box$lon, lat=box$lat, date="last", field="chl")
# map_raster(r, site_lon=site$lon, site_lat=site$lat, site_label=site$name, title="CHL")

# bounding box offset around site marker for extent of map
b_2 <- 3.0

leaflet(
  options = leafletOptions(
    crs_2 = leafletCRS(crsClass = "L.CRS.EPSG4326"))) %>%
  # basemap from GBIF in 4326
  addTiles("//tile.gbif.org/4326/omt/{z}/{x}/{y}@1x.png?style=gbif-geyser") %>%
  # sst
  addWMSTiles(
    baseUrl = 'https://coastwatch.pfeg.noaa.gov/erddap/wms/nesdisVHNSQchlaMonthly/request?',
    layers = "nesdisVHNSQchlaMonthly:chlor_a",
    options = WMSTileOptions(
      version = "1.3.0", format = "image/png", transparent = T, opacity = 0.7,
      time = format(d_2,"%Y-%m-%dT00:00:00Z")))  %>%
  addMarkers(lng = ~lon, lat = ~lat, label = ~name, data=site) %>%
  addMouseCoordinates() %>%
  fitBounds(site$lon - b_2, site$lat - b_2, site$lon + b_2, site$lat + b_2) %>%
  addLegend(
    position="bottomright",
    title = paste0("CHL (mg m^-3)<br>", format(d_2,"%Y-%m-%d")),
    colorNumeric("Spectral", c(0,4), reverse=T), seq(0,4))
```
## Timeseries of CHL

```{r, echo=FALSE, message=FALSE, warning=FALSE}
csv <- here(glue("data/chl/chl_{site$id}.csv"))
d_2   <- get_timeseries(chl, lon=site$lon, lat=site$lat, csv=csv, field="chlor_a")
plot_timeseries(d_2, title="CHL", color="green")
```
